name:                funcpaper
version:             0.1.0.0
github:              "vovapolu/funcpaper"
license:             BSD3
author:              "vovapolu"
maintainer:          "vovapolu@gmail.com"
copyright:           "2018 Vladimir Polushin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vovapolu/funcpaper/#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- MonadRandom

library:
  source-dirs: src

executables:
  funcpaper:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funcpaper

tests:
  funcpaper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funcpaper
